package arrayexample;

public class test {
	/*public static void main(String []args){  
        try{  
            int a = 1;   
            System.out.println(a/0);  
        }  catch(Exception e) {}
        finally  
        {  
            System.out.println("rest of the code...");  
        }  
     
        System.out.println("rest of the code.......");  

	
	
		
		
	} */
	
	
	//146) What is exception propagation?
	//https://www.javatpoint.com/corejava-interview-questions-2
	void m(){  
	    int data=50/0;  
	    System.out.println("in M");
	  }  
	  void n(){  
	    m();  
	    System.out.println("in N");

	  }  
	  void p(){  
	   try{  
	    n();  
	    System.out.println("in P");

	   }catch(Exception e){System.out.println("exception handled");
	   }
	   
	    System.out.println("Handeled in P...so normal flow of P started");

	   
	  }  
	  public static void main(String args[]){  
		  test obj=new test();  
	   obj.p();  
	   System.out.println("normal flow...in main");  
	  }  

}
